require 'json'

file = File.read('')

my_profile_view
my_profile_edit_bio
my_profile_edit_intent
my_profile_add_experience
my_profile_add_education
my_profile_add_social_media
my_profile_edit_interests
my_profile_edit_skills
my_profile_edit_portfolio
my_profile_edit_name
my_profile_edit_email
insights_view
influence_rank_view

connection_add_by_name_view
connection_scan_id_view


#sequence 
app_open
feed_view
my_profile_view
settings_view
my_profile_edit_email
settings_view
my_profile_edit_name
my_profile_edit_intent
my_profile_edit_bio
my_profile_add_experience
my_profile_add_education